# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
    App\Tests\:
        resource: '../tests/'
        autowire: true
        autoconfigure: true
        exclude:
            - '../tests/bootstrap.php'
